AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

# Disable some cops that are too strict for this project
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120

# Allow some Rails-specific patterns
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

# Allow some common patterns
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

# Allow some test patterns
Style/BlockDelimiters:
  Enabled: false

# Allow some migration patterns
Style/NumericLiterals:
  Enabled: false
